/**
 * Hook for syncing Remotion animations with voiceover timestamps
 */

import { useCurrentFrame } from "remotion";

interface WordTimestamp {
  word: string;
  start: number;
  end: number;
  startFrame: number;
  endFrame: number;
}

interface SectionTimestamp {
  section: string;
  start: number;
  end: number;
  startFrame: number;
  endFrame: number;
  words: WordTimestamp[];
}

interface VoiceoverTimestamps {
  words: WordTimestamp[];
  sections: SectionTimestamp[];
  fps: number;
}

// Import generated timestamps (after running generate-voice.ts)
let timestamps: VoiceoverTimestamps | null = null;

try {
  // This will be generated by generate-voice.ts
  timestamps = require("./voiceover-timestamps.json");
} catch {
  console.warn("No voiceover-timestamps.json found. Run generate-voice.ts first.");
}

export function useVoiceoverSync() {
  const frame = useCurrentFrame();

  /**
   * Get the current section based on frame
   */
  const getCurrentSection = (): SectionTimestamp | null => {
    if (!timestamps) return null;
    return timestamps.sections.find(
      (s) => frame >= s.startFrame && frame <= s.endFrame
    ) || null;
  };

  /**
   * Get the current word being spoken
   */
  const getCurrentWord = (): WordTimestamp | null => {
    if (!timestamps) return null;
    return timestamps.words.find(
      (w) => frame >= w.startFrame && frame <= w.endFrame
    ) || null;
  };

  /**
   * Check if a section has started
   */
  const isSectionActive = (sectionName: string): boolean => {
    if (!timestamps) return false;
    const section = timestamps.sections.find((s) => s.section === sectionName);
    return section ? frame >= section.startFrame : false;
  };

  /**
   * Check if we're currently IN a section (not just past it)
   */
  const isInSection = (sectionName: string): boolean => {
    if (!timestamps) return false;
    const section = timestamps.sections.find((s) => s.section === sectionName);
    return section ? frame >= section.startFrame && frame <= section.endFrame : false;
  };

  /**
   * Get opacity for an element that should appear when a section starts
   * Fades in over specified frames
   */
  const getSectionOpacity = (
    sectionName: string,
    fadeInFrames: number = 8
  ): number => {
    if (!timestamps) return 0;
    const section = timestamps.sections.find((s) => s.section === sectionName);
    if (!section) return 0;

    if (frame < section.startFrame) return 0;

    const progress = (frame - section.startFrame) / fadeInFrames;
    return Math.min(1, progress);
  };

  /**
   * Get start frame for a section (for camera keyframes)
   */
  const getSectionStartFrame = (sectionName: string): number => {
    if (!timestamps) return 0;
    const section = timestamps.sections.find((s) => s.section === sectionName);
    return section?.startFrame || 0;
  };

  /**
   * Generate camera keyframes based on section timing
   * Returns keyframes compatible with existing camera system
   */
  const generateCameraKeyframes = (sectionPositions: {
    [key: string]: { x: number; y: number; scale: number };
  }) => {
    if (!timestamps) return [];

    return timestamps.sections.map((section) => ({
      frame: section.startFrame,
      ...sectionPositions[section.section],
    }));
  };

  return {
    frame,
    timestamps,
    getCurrentSection,
    getCurrentWord,
    isSectionActive,
    isInSection,
    getSectionOpacity,
    getSectionStartFrame,
    generateCameraKeyframes,
  };
}

/**
 * Get all sections with their timing
 * Useful for updating Root.tsx duration
 */
export function getVoiceoverDuration(): number {
  if (!timestamps) return 330; // Default fallback
  const lastSection = timestamps.sections[timestamps.sections.length - 1];
  // Add 60 frames (2 seconds) buffer at the end
  return lastSection ? lastSection.endFrame + 60 : 330;
}
